# -*- coding: utf-8 -*-
"""cross domain linking

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11zEL355rYykNxK5SL1I-34kzkdxYMYQL
"""

# Step 0: Imports
from sentence_transformers import SentenceTransformer
import torch
from torch import nn
import pandas as pd
import networkx as nx
import matplotlib.pyplot as plt

# -------------------------------
# Step 1: Load your cleaned datasets
# -------------------------------
# Replace these with your actual cleaned data
domainA_texts = ["Fake news A1", "Fake news A2", "Fake news A3"]
domainB_texts = ["Fake news B1", "Fake news B2", "Fake news B3"]

# -------------------------------
# Step 2: Encode texts to embeddings
# -------------------------------
model = SentenceTransformer('all-MiniLM-L6-v2')
embeddings_domainA = model.encode(domainA_texts, convert_to_tensor=True)
embeddings_domainB = model.encode(domainB_texts, convert_to_tensor=True)

# -------------------------------
# Step 3: Compute cosine similarity and create cross-domain links
# -------------------------------
cos = nn.CosineSimilarity(dim=1)
top_k = 3  # Number of top matches to link
threshold = 0.7  # Optional similarity threshold

links = []
for i, embA in enumerate(embeddings_domainA):
    similarities = cos(embA.unsqueeze(0), embeddings_domainB)
    topk = torch.topk(similarities, k=top_k)

    linked_texts = [(idx.item(), sim.item()) for idx, sim in zip(topk.indices, topk.values) if sim.item() > threshold]
    if linked_texts:
        links.append({'domainA_index': i, 'linked_B': linked_texts})

# -------------------------------
# Step 4: Export cross-domain links to CSV
# -------------------------------
rows = []
for link in links:
    a_idx = link['domainA_index']
    textA = domainA_texts[a_idx]
    for b_idx, sim in link['linked_B']:
        textB = domainB_texts[b_idx]
        rows.append({'DomainA_index': a_idx, 'DomainA_text': textA,
                     'DomainB_index': b_idx, 'DomainB_text': textB,
                     'Similarity': sim})

df_links = pd.DataFrame(rows)
df_links.to_csv("cross_domain_links.csv", index=False)
print("CSV file 'cross_domain_links.csv' created successfully!")
print(df_links.head())

# -------------------------------
# Step 5: Optional: Build & visualize graph
# -------------------------------
G = nx.Graph()
for i in range(len(domainA_texts)):
    G.add_node(f"A{i}", label=domainA_texts[i], domain='A')
for j in range(len(domainB_texts)):
    G.add_node(f"B{j}", label=domainB_texts[j], domain='B')

for link in links:
    a_node = f"A{link['domainA_index']}"
    for b_idx, sim in link['linked_B']:
        b_node = f"B{b_idx}"
        G.add_edge(a_node, b_node, weight=sim)

pos = nx.spring_layout(G, seed=42)
colors = ['skyblue' if G.nodes[n]['domain']=='A' else 'lightgreen' for n in G.nodes()]

plt.figure(figsize=(10,7))
nx.draw(G, pos, with_labels=True, node_color=colors, node_size=1200, font_size=10, font_weight='bold')
edge_labels = {(u, v): f"{d['weight']:.2f}" for u, v, d in G.edges(data=True)}
nx.draw_networkx_edge_labels(G, pos, edge_labels=edge_labels, font_color='red')
plt.title("Cross-Domain Links Between Domain A and B News")
plt.show()